---
mosquitto: false

hass: false
# renovate: datasource=docker depName=linuxserver/homeassistant
hass_version: 2026.1.0
hass_image: "linuxserver/homeassistant:{{ hass_version }}"
hass_config_local_dir: /srv/hass
hass_config_branch: main
hass_config_repo: false
hass_deploy_key: false
hass_hostname: "hass"
hass_db_user: hass
hass_db_password: hass
hass_db_name: hass
hass_db_port: 5432
hass_db_host: postgres
hass_devices: []

authelia: false
authelia_dir: /srv/authelia
# renovate: datasource=docker depName=authelia/authelia
authelia_version: 4.39.15
authelia_db_user: authelia
authelia_db_pass: authelia
authelia_db_name: authelia

authentik: false
# renovate: datasource=docker depName=ghcr.io/goauthentik/server
authentik_version: 2025.10.3
authentik_image: "ghcr.io/goauthentik/server:{{ authentik_version }}"
authentik_dir: "/srv/authentik"
authentik_state: present
authentik_env: {}
