---
portainer: false
portainer_edition: ce
portainer_agent: false

# renovate: datasource=docker depName=portainer/portainer-ee
portainer_ee_version: 2.36.0
portainer_ee_image: "portainer/portainer-ee:{{ portainer_ee_version }}"

# renovate: datasource=docker depName=portainer/portainer-ce
portainer_ce_version: 2.37.0
portainer_ce_image: "portainer/portainer-ce:{{ portainer_ce_version }}"
portainer_hostname: portainer

# renovate: datasource=docker depName=portainer/agent
portainer_agent_version: 2.36.0
portainer_agent_image: "portainer/agent:{{ portainer_agent_version }}"

# renovate: datasource=docker depName=linuxserver/duplicati
duplicati_version: latest@sha256:22bae5a2a80ef48c8b2833e6887f72566491c8d383c0656111f7fdf78012c575
duplicati_encryption_key: secret
duplicati_password: secret

# renovate: datasource=docker depName=ghcr.io/kilip/semaphore
semaphore_version: v2.16.45
semaphore_env: {}
sempahore_runner_env: {}

newrelic: false
