---
postgres: false
# renovate: datasource=docker depName=postgis/postgis
pg_version: 18-3.6-alpine
pg_image: "postgis/postgis:{{ pg_version }}"
pg_user: homelab
pg_pass: homelab
pg_db: homelab
pg_host: homelab

# renovate: datasource=docker depName=redis
redis_version: 8.6.0
redis_image: "redis:{{ redis_version }}-alpine"

# renovate: datasource=docker depName=quay.io/minio/minio
minio_version: RELEASE.2025-09-07T16-13-09Z
minio: false
minio_user: minio
minio_pass: minio
